name: Update Quote of the Day

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at 00:00 UTC (1am WAT)
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run script to update quote
        run: node scripts/update-quote.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🧠 auto: update quote of the day"
          git push
          echo "✨ Done at $(date -u)"
