name: Refresh Profile README

on:
  schedule:
    - cron: "0 0 * * *" # re-runs once daily at midnight UTC
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Reset to latest origin/main
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run script to update README
        run: node scripts/update-readme.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🔄 auto: update latest repos"
          git push || echo "⚠️ Push failed, maybe nothing to push"
          echo "✨ Done at $(date -u)"
